title: My cool site
description: Text about my cool site
images:
  - site-feature-image.jpg

license:
  title_of_work: This website
  link_to_work: https://mozo.kr
  createor_of_work: mozodev
  link_to_creator_profile: https://github.com/mozodev
  year_of_creation: 2021
